spring:
  application:
    name: task28
  datasource:
    url: jdbc:mysql://localhost:3306/task28
    username: root
    password: verysecret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true